In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
train_data_gen = ImageDataGenerator(rescale=1.0/255,validation_split=0.3)

In [3]:
training_Data = train_data_gen.flow_from_directory(
    "/content/drive/MyDrive/PIAIC/flower-recognition",
    target_size=(150,150), 
    batch_size=5,
    shuffle=True,
     subset="training",
    class_mode='categorical'
)
validation_Data = train_data_gen.flow_from_directory(
    "/content/drive/MyDrive/PIAIC/flower-recognition",
    target_size=(150,150),
    batch_size=5,
    shuffle=True,
    class_mode='categorical',
     subset='validation'
)

Found 3210 images belonging to 5 classes.
Found 1373 images belonging to 5 classes.


In [4]:
# validation_Data.labels[0:300]

In [5]:
# validation_Data = tf.keras.preprocessing.image_dataset_from_directory(
#     "/content/drive/MyDrive/PIAIC/flower-recognition",
#     labels='inferred',
#     label_mode="int",
#     class_names=['daisy','dandelion', 'rose', 'sunflower','tulip'],
#     color_mode="rgb",
#     batch_size=32,
#     image_size=(150,150),
#     shuffle=True,
#     seed=1234,
#     validation_split= 0.3,
#     subset='validation',
#     interpolation="bilinear",
#     follow_links=False
# )
# training_Data = tf.keras.preprocessing.image_dataset_from_directory(
#     "/content/drive/MyDrive/PIAIC/flower-recognition",
#     labels='inferred',
#     label_mode="int",
#     class_names=['daisy','dandelion', 'rose', 'sunflower','tulip'],
#     color_mode="rgb",
#     batch_size=32,
#     image_size=(150,150),
#     shuffle=True,
#     seed=1234,
#     validation_split= 0.3,
#     subset='training',
#     interpolation="bilinear",
#     follow_links=False
# )

In [6]:
training_Data

In [7]:
# from google.colab import drive
# drive.mount('/content/drive')

In [8]:
# training_Data.class_indices

In [9]:
import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
import tensorflow_datasets as tfds

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import RMSprop

In [11]:
# # model with Dense layers
# model = models.Sequential()
# model.add(Flatten())
# model.add(layers.Dense(64, activation='relu'))
# model.add(layers.Dense(46, activation='relu'))
# model.add(Dense(5, activation='softmax'))

In [12]:
#MOdels with COnv2D and Maxpooling
model = tf.keras.models.Sequential([
    # Note the input shape is the desired size of the image 150x150 with 3 bytes color
    # This is the first convolution
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    # The second convolution
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    # The third convolution
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    # The fourth convolution
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    # Flatten the results to feed into a DNN
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5),
    # 512 neuron hidden layer
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])

In [25]:
model.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [26]:
# model.fit(
#     training_Data,
#     batch_size=10,
#     epochs = 20)

model.fit(
    training_Data,
    steps_per_epoch = 20,
    validation_data = validation_Data, 
    validation_steps = 20,
    epochs = 5)

#model.fit(training_Data,batch_size=100,epochs=70)

Epoch 1/5
 4/20 [=====>........................] - ETA: 18s - loss: 2.2521 - accuracy: 0.4208

KeyboardInterrupt: ignored

In [15]:
# from google.colab import drive
# drive.mount('/content/drive')

In [16]:
Y = model.predict(validation_Data)
Y

array([[0.12963153, 0.16602468, 0.2690266 , 0.15153348, 0.2837837 ],
       [0.1568507 , 0.18438411, 0.23451811, 0.17104879, 0.25319836],
       [0.11712683, 0.14303873, 0.3220971 , 0.12038958, 0.29734775],
       ...,
       [0.1277288 , 0.16994601, 0.25196525, 0.15754203, 0.29281792],
       [0.08373991, 0.11503736, 0.37359646, 0.08456963, 0.34305668],
       [0.07625944, 0.09920026, 0.40473196, 0.07181732, 0.347991  ]],
      dtype=float32)

In [22]:
predict_class = np.argmax(Y, axis=1)
#predict_class = predict_class.tolist()
predict_class[0:300]

array([4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 4, 2, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2, 2, 4, 4, 2, 4,
       4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2,
       4, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [21]:
validation_Data.labels[0:300]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], d

In [28]:
con = tf.math.confusion_matrix(labels= validation_Data.labels, predictions= predict_class )

In [29]:
con

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   0,  35,   0, 195],
       [  0,   0,  52,   0, 263],
       [  0,   0,  30,   0, 253],
       [  0,   0,  41,   0, 209],
       [  0,   0,  40,   0, 255]], dtype=int32)>